#---------------------------------#
#       build configuration       #
#---------------------------------#

configuration: Release

build:
  project: AppVeyorSandbox.sln

before_build:
  - nuget restore

#---------------------------------#
#      artifacts configuration    #
#---------------------------------#

artifacts:
  - path: AppVeyorSandbox\bin\Release